import { User, Role, ClubRole, Club, Applicant, Event, AuditLog, Registration } from './types';

// ─── DEMO USERS ─────────────────────────────────────────────────────────────
// Student demo is President of CSIT Club (club-csit)
export const DEMO_USERS: User[] = [
  {
    id: 'demo-student-001',
    name: 'Aryan Sharma',
    email: 'aryan@mitsgwl.ac.in',
    password: 'DEMO-PASS',
    globalRole: Role.STUDENT,
    clubMemberships: [
      { clubId: 'club-csit', role: ClubRole.PRESIDENT },
      { clubId: 'club-robo', role: ClubRole.MEMBER },
    ],
    enrollmentNumber: '0901CS211001',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    phoneNumber: '9876543210',
    skills: ['React', 'Node.js', 'MongoDB', 'Python'],
    linkedin: 'https://linkedin.com/in/aryan-sharma',
    github: 'https://github.com/aryan-sharma',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Signature_of_Theodore_Roosevelt.svg/2560px-Signature_of_Theodore_Roosevelt.svg.png'
  },
  {
    id: 'demo-faculty-001',
    name: 'Dr. Priya Verma',
    email: 'priya.verma@mitsgwl.ac.in',
    password: 'DEMO-PASS',
    globalRole: Role.FACULTY,
    clubMemberships: [],
    enrollmentNumber: 'FAC-2024-01',
    branch: 'Information Technology',
    department: 'Information Technology',
    designation: 'Associate Professor',
    phoneNumber: '9123456780',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png'
  },
  {
    id: 'demo-dean-001',
    name: 'Dr. Manish Dixit',
    email: 'dean.sw@mitsgwl.ac.in',
    password: 'DEMO-PASS',
    globalRole: Role.DEAN,
    clubMemberships: [],
    enrollmentNumber: 'DEAN-SW-01',
    branch: 'Dean Student Welfare',
    department: 'Dean Student Welfare',
    designation: 'Dean of Student Welfare',
    phoneNumber: '9000000001',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Signature_of_Theodore_Roosevelt.png'
  },
  {
    id: 'demo-admin-001',
    name: 'Admin (Demo)',
    email: 'admin@mitsgwl.ac.in',
    password: 'DEMO-PASS',
    globalRole: Role.SUPER_ADMIN,
    clubMemberships: [],
    enrollmentNumber: 'ADMIN-ROOT',
    department: 'Institutional Operations',
    designation: 'Platform Administrator',
    phoneNumber: '9001112223',
  },
  // Demo users for quick login
  {
    id: 'demo-student-example',
    name: 'Demo Student',
    email: 'demo-student@example.com',
    password: 'DEMO-PASS',
    globalRole: Role.STUDENT,
    clubMemberships: [
      { clubId: 'club-csit', role: ClubRole.MEMBER },
    ],
    enrollmentNumber: 'DEMO-STU-001',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    phoneNumber: '9999999999',
    skills: ['Test Automation', 'UI Design', 'Campus Operations'],
    linkedin: 'https://linkedin.com/in/demo-student',
    github: 'https://github.com/demo-student',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Signature_example.svg'
  },
  {
    id: 'demo-faculty-example',
    name: 'Demo Faculty',
    email: 'demo-faculty@example.com',
    password: 'DEMO-PASS',
    globalRole: Role.FACULTY,
    clubMemberships: [],
    enrollmentNumber: 'DEMO-FAC-001',
    branch: 'Information Technology',
    department: 'Information Technology',
    designation: 'Assistant Professor',
    phoneNumber: '8888888888',
    linkedin: 'https://linkedin.com/in/demo-faculty',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png'
  },
  {
    id: 'demo-admin-example',
    name: 'Demo Admin',
    email: 'demo-admin@example.com',
    password: 'DEMO-PASS',
    globalRole: Role.SUPER_ADMIN,
    clubMemberships: [],
    enrollmentNumber: 'DEMO-ADMIN-001',
    department: 'Campus Systems',
    designation: 'Super Admin',
    phoneNumber: '7777777777'
  },
];

// ─── ALL USERS (shown in registries) ─────────────────────────────────────────
export const SEED_USERS: User[] = [
  ...DEMO_USERS,
  {
    id: 'stu-002',
    name: 'Sneha Jain',
    email: 'sneha@mitsgwl.ac.in',
    password: 'SN3HA-X9',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-csit', role: ClubRole.VICE_PRESIDENT }],
    enrollmentNumber: '0901CS211002',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    phoneNumber: '9876501234',
    skills: ['UI/UX', 'Figma', 'JavaScript', 'Responsive Design'],
    linkedin: 'https://linkedin.com/in/sneha-jain-2024',
    github: 'https://github.com/snehajain',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png',
    address: 'MITS Campus, Gwalior, MP',
    fatherName: 'Rajesh Jain',
    motherName: 'Neha Jain',
  },
  {
    id: 'stu-003',
    name: 'Rahul Mishra',
    email: 'rahul@mitsgwl.ac.in',
    password: 'RH-M1SH',
    globalRole: Role.STUDENT,
    clubMemberships: [
      { clubId: 'club-robo', role: ClubRole.PRESIDENT },
      { clubId: 'club-csit', role: ClubRole.MEMBER },
    ],
    enrollmentNumber: '0901EC211003',
    branch: 'Electronics & Communication',
    department: 'Electronics & Communication',
    phoneNumber: '9812345678',
    skills: ['Arduino', 'C++', 'Embedded Systems', 'Robotics'],
    linkedin: 'https://linkedin.com/in/rahul-mishra-robo',
    github: 'https://github.com/rahulmishra98',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Signature_of_Theodore_Roosevelt.png',
    address: 'Lashkar, Gwalior, MP',
    fatherName: 'Surendra Mishra',
    motherName: 'Sunita Mishra',
  },
  {
    id: 'stu-004',
    name: 'Anjali Gupta',
    email: 'anjali@mitsgwl.ac.in',
    password: 'ANJ-G9PT',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-cultural', role: ClubRole.SECRETARY }],
    enrollmentNumber: '0901CE211004',
    branch: 'Civil Engineering',
    department: 'Civil Engineering',
    phoneNumber: '9988776655',
    skills: ['Event Management', 'Dance', 'Music', 'Organization'],
    linkedin: 'https://linkedin.com/in/anjali-gupta-cultural',
    github: 'https://github.com/anjaligupta',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Signature_of_Theodore_Roosevelt.svg/2560px-Signature_of_Theodore_Roosevelt.svg.png',
    address: 'Dwarka Nagar, Gwalior, MP',
    fatherName: 'Arun Gupta',
    motherName: 'Priya Gupta',
  },
  {
    id: 'stu-005',
    name: 'Vikram Tiwari',
    email: 'vikram@mitsgwl.ac.in',
    password: 'VK-T1W4',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-sports', role: ClubRole.PRESIDENT }],
    enrollmentNumber: '0901ME211005',
    branch: 'Mechanical Engineering',
    department: 'Mechanical Engineering',
    phoneNumber: '9765432109',
    skills: ['Football', 'Cricket', 'Athletic Training', 'Fitness Management'],
    linkedin: 'https://linkedin.com/in/vikram-tiwari-sports',
    github: 'https://github.com/vikramtiwari',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png',
    address: 'University Lane, Gwalior, MP',
    fatherName: 'Vinay Tiwari',
    motherName: 'Vandana Tiwari',
  },
  {
    id: 'stu-006',
    name: 'Pooja Choudhary',
    email: 'pooja@mitsgwl.ac.in',
    password: 'PJ-CH0D',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-csit', role: ClubRole.TECH_HEAD }],
    enrollmentNumber: '0901CS211006',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    phoneNumber: '9876543321',
    skills: ['Python', 'Machine Learning', 'Data Science', 'TensorFlow'],
    linkedin: 'https://linkedin.com/in/pooja-choudhary-ml',
    github: 'https://github.com/poojachoudhary',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Signature_of_Theodore_Roosevelt.png',
    address: 'Phool Bagh, Gwalior, MP',
    fatherName: 'Prem Choudhary',
    motherName: 'Poonam Choudhary',
  },
  {
    id: 'stu-007',
    name: 'Amit Dubey',
    email: 'amit@mitsgwl.ac.in',
    password: 'AM-D9BY',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-robo', role: ClubRole.TECH_HEAD }],
    enrollmentNumber: '0901EE211007',
    branch: 'Electrical Engineering',
    department: 'Electrical Engineering',
    phoneNumber: '9765401234',
    skills: ['IoT', 'PCB Design', 'Raspberry Pi', '3D Modeling'],
    linkedin: 'https://linkedin.com/in/amit-dubey-iot',
    github: 'https://github.com/amitdubey',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Signature_of_Theodore_Roosevelt.svg/2560px-Signature_of_Theodore_Roosevelt.svg.png',
    address: 'Madhav Vihar, Gwalior, MP',
    fatherName: 'Ashok Dubey',
    motherName: 'Anita Dubey',
  },
  {
    id: 'stu-008',
    name: 'Kavya Sharma',
    email: 'kavya@mitsgwl.ac.in',
    password: 'KV-SH8M',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-cultural', role: ClubRole.PRESIDENT }],
    enrollmentNumber: '0901CS221008',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    phoneNumber: '9988776610',
    skills: ['Theatre', 'Creative Writing', 'Photography', 'Content Creation'],
    linkedin: 'https://linkedin.com/in/kavya-sharma-artist',
    github: 'https://github.com/kavya-creative',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png',
    address: 'Akela Khas, Gwalior, MP',
    fatherName: 'Ramesh Sharma',
    motherName: 'Kavita Sharma',
  },
  {
    id: 'stu-009',
    name: 'Rohit Saxena',
    email: 'rohit@mitsgwl.ac.in',
    password: 'RH-SX9N',
    globalRole: Role.STUDENT,
    clubMemberships: [],
    enrollmentNumber: '0901CE221009',
    branch: 'Civil Engineering',
    department: 'Civil Engineering',
    phoneNumber: '9654321087',
    skills: ['AutoCAD', 'SketchUp', 'Structural Design', 'BIM'],
    linkedin: 'https://linkedin.com/in/rohit-saxena-cad',
    github: 'https://github.com/rohitsaxena',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Signature_of_Theodore_Roosevelt.png',
    address: 'Rajendra Nagar, Gwalior, MP',
    fatherName: 'Rajesh Saxena',
    motherName: 'Rekha Saxena',
  },
  {
    id: 'stu-010',
    name: 'Priya Singh',
    email: 'priya.s@mitsgwl.ac.in',
    password: 'PR-SNGH',
    globalRole: Role.STUDENT,
    clubMemberships: [{ clubId: 'club-robo', role: ClubRole.MANAGEMENT_HEAD }],
    enrollmentNumber: '0901EC221010',
    branch: 'Electronics & Communication',
    department: 'Electronics & Communication',
    phoneNumber: '9812345699',
    skills: ['VLSI', 'Verilog', 'MATLAB', 'Circuit Design'],
    linkedin: 'https://linkedin.com/in/priya-singh-vlsi',
    github: 'https://github.com/priyasingh',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Signature_of_Theodore_Roosevelt.svg/2560px-Signature_of_Theodore_Roosevelt.svg.png',
    address: 'Vijaypuri, Gwalior, MP',
    fatherName: 'Suresh Singh',
    motherName: 'Sushma Singh',
  },
  {
    id: 'fac-001',
    name: 'Prof. Suresh Kumar',
    email: 'suresh.k@mitsgwl.ac.in',
    password: 'FAC-SK01',
    globalRole: Role.FACULTY,
    clubMemberships: [],
    enrollmentNumber: 'FAC-2023-01',
    branch: 'Computer Science & IT',
    department: 'Computer Science & IT',
    designation: 'Associate Professor',
    phoneNumber: '9876504321',
    linkedin: 'https://linkedin.com/in/suresh-kumar-cse',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Signature_of_John_Hancock.png',
    address: 'Faculty Quarters, MITS, Gwalior',
    fatherName: 'Shyam Kumar',
    motherName: 'Sunita Rani',
  },
  {
    id: 'fac-002',
    name: 'Dr. Anita Patel',
    email: 'anita.p@mitsgwl.ac.in',
    password: 'FAC-AP02',
    globalRole: Role.FACULTY,
    clubMemberships: [],
    enrollmentNumber: 'FAC-2023-02',
    branch: 'Electronics & Communication',
    department: 'Electronics & Communication',
    designation: 'Assistant Professor',
    phoneNumber: '9123409876',
    linkedin: 'https://linkedin.com/in/anita-patel-ece',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Signature_of_Theodore_Roosevelt.png',
    address: 'Faculty Quarters, MITS, Gwalior',
    fatherName: 'Anil Patel',
    motherName: 'Anjali Patel',
  },
  {
    id: 'fac-003',
    name: 'Prof. Rajesh Bharti',
    email: 'rajesh.b@mitsgwl.ac.in',
    password: 'FAC-RB03',
    globalRole: Role.FACULTY,
    clubMemberships: [],
    enrollmentNumber: 'FAC-2022-03',
    branch: 'Mechanical Engineering',
    department: 'Mechanical Engineering',
    designation: 'Assistant Professor',
    phoneNumber: '8765432190',
    linkedin: 'https://linkedin.com/in/rajesh-bharti-me',
    signatureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Signature_of_Theodore_Roosevelt.svg/2560px-Signature_of_Theodore_Roosevelt.svg.png',
    address: 'Faculty Quarters, MITS, Gwalior',
    fatherName: 'Rajendra Bharti',
    motherName: 'Rupali Bharti',
  },
];

// ─── CLUBS ────────────────────────────────────────────────────────────────────
export const CLUBS: Club[] = [
  {
    id: 'club-csit',
    name: 'CSIT Club',
    category: 'Technical',
    themeColor: '#0099FF',
    subdomain: 'csit',
    logoUrl: '',
    facultyCoordinatorId: 'fac-001',
    facultyCoordinatorNames: ['Prof. Suresh Kumar'],
    leadership: {
      President: 'Aryan Sharma',
      'Vice President': 'Sneha Jain',
      'Tech Head': 'Pooja Choudhary',
    },
    tagline: 'Code. Create. Conquer.',
    bannerUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200',
    description:
      'The premier technical club of MITS Gwalior, focused on software development, competitive programming, and technology innovation. We organize hackathons, coding bootcamps, and workshops throughout the year.',
    recruitmentActive: true,
    achievements: [
      { id: 'a1', title: 'Smart India Hackathon – Regional Winners', description: 'Won SIH regional round 2023 with project on Smart Agriculture using IoT', date: '2023-12-01' },
      { id: 'a2', title: '500+ Students Trained', description: 'Conducted 20+ workshops on Web Dev, ML, Cloud & DevOps', date: '2024-01-15' },
      { id: 'a3', title: 'Google Solution Challenge – Top 100', description: 'Our team reached Global Top 100 in GDSC Solution Challenge 2024', date: '2024-03-20' },
      { id: 'a4', title: 'ICPC Regionals Qualifier', description: '3 teams qualified for ICPC Asia-West Regional Contest', date: '2024-02-10' },
    ],
    customSections: [
      { id: 'cs1', title: 'Our Mission', content: 'To bridge the gap between classroom learning and industry-ready skills by providing hands-on experience in cutting-edge technologies.', iconName: 'Target' },
      { id: 'cs2', title: 'What We Offer', content: 'Weekly coding sessions, monthly hackathons, industry mentorship, project-based learning, competitive programming training, and placement prep workshops.', iconName: 'BookOpen' },
      { id: 'cs3', title: 'Tech Stack Focus', content: 'React, Node.js, Python, TensorFlow, AWS, Docker, Kubernetes, Flutter, PostgreSQL, MongoDB & more.', iconName: 'Code' },
    ],
    certificateConfig: {
      templateId: 'modern',
      showMITSLogo: true,
      showClubLogo: true,
      signatureTextFaculty: 'Prof. Suresh Kumar - Faculty Coordinator',
      signatureTextPresident: 'Aryan Sharma - Club President',
    },
  },
  {
    id: 'club-robo',
    name: 'Robotics Club',
    category: 'Technical',
    themeColor: '#10B981',
    subdomain: 'robotics',
    logoUrl: '',
    facultyCoordinatorId: 'fac-002',
    facultyCoordinatorNames: ['Dr. Anita Patel'],
    leadership: {
      President: 'Rahul Mishra',
      'Tech Head': 'Amit Dubey',
      'Management Head': 'Priya Singh',
    },
    tagline: 'Build. Automate. Innovate.',
    bannerUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200',
    description:
      'Focused on robotics, IoT and embedded systems, we build real-world automation solutions and participate in national-level competitions. From line followers to autonomous drones, we push boundaries.',
    recruitmentActive: true,
    achievements: [
      { id: 'b1', title: 'Robocon 2024 – Semifinalists', description: 'Reached semifinals at national level Robocon competition', date: '2024-03-10' },
      { id: 'b2', title: 'e-Yantra IIT Bombay – Stage 2', description: 'Cleared Stage 2 of e-Yantra robotics competition by IIT Bombay', date: '2024-01-20' },
      { id: 'b3', title: 'Smart India Hackathon Hardware – Winners', description: 'Won SIH Hardware round with a smart irrigation system', date: '2023-12-15' },
    ],
    customSections: [
      { id: 'rs1', title: 'Lab & Equipment', content: 'Fully equipped lab with 3D printers, CNC machines, Arduino/Raspberry Pi kits, drone assembly stations, and soldering workstations.', iconName: 'Wrench' },
      { id: 'rs2', title: 'Projects', content: 'Currently working on: Autonomous delivery bot, Smart greenhouse, Line-following swarm robots, and Gesture-controlled robotic arm.', iconName: 'Cpu' },
    ],
    certificateConfig: {
      templateId: 'tech',
      showMITSLogo: true,
      showClubLogo: true,
      signatureTextFaculty: 'Dr. Anita Patel - Faculty Coordinator',
      signatureTextPresident: 'Rahul Mishra - Club President',
    },
  },
  {
    id: 'club-cultural',
    name: 'Cultural Club',
    category: 'Cultural',
    themeColor: '#F59E0B',
    subdomain: 'cultural',
    logoUrl: '',
    facultyCoordinatorId: 'demo-faculty-001',
    facultyCoordinatorNames: ['Dr. Priya Verma'],
    leadership: {
      President: 'Kavya Sharma',
      Secretary: 'Anjali Gupta',
    },
    tagline: 'Art. Expression. Unity.',
    bannerUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200',
    description:
      'Celebrating the cultural diversity of MITS through music, dance, drama and literary events. We are the heartbeat of campus life, organizing Rangmanch and other flagship festivals.',
    recruitmentActive: false,
    achievements: [
      { id: 'c1', title: 'Rangmanch 2024 – Record Footfall', description: '3000+ attendees at annual cultural festival', date: '2024-04-05' },
      { id: 'c2', title: 'Inter-College Dance Championship', description: 'Won 1st place at Techno-Cultural Fest, IIIT Bhopal', date: '2024-02-28' },
      { id: 'c3', title: 'National Drama Competition', description: 'Represented MP state in National Youth Festival drama category', date: '2024-01-10' },
    ],
    customSections: [
      { id: 'cc1', title: 'Wings', content: 'Dance Wing, Music Wing, Drama & Theatre Wing, Literary Wing, Art & Design Wing, Photography Wing.', iconName: 'Star' },
      { id: 'cc2', title: 'Flagship Events', content: 'Rangmanch (Annual Fest), Open Mic Nights, Cultural Weekends, Flash Mobs, Heritage Walks, and Artist-in-Residence programs.', iconName: 'Calendar' },
    ],
    certificateConfig: {
      templateId: 'elegant',
      showMITSLogo: true,
      showClubLogo: true,
      signatureTextFaculty: 'Dr. Priya Verma - Faculty Coordinator',
      signatureTextPresident: 'Kavya Sharma - Club President',
    },
  },
  {
    id: 'club-sports',
    name: 'Sports Committee',
    category: 'Sports',
    themeColor: '#EF4444',
    subdomain: 'sports',
    logoUrl: '',
    facultyCoordinatorId: 'fac-003',
    facultyCoordinatorNames: ['Prof. Rajesh Bharti'],
    leadership: {
      President: 'Vikram Tiwari',
    },
    tagline: 'Sweat. Compete. Win.',
    bannerUrl: 'https://images.unsplash.com/photo-1461896836934-bd45ba8b2bfc?w=1200',
    description:
      'Organizing intra and inter-college sports events, tournaments and fitness programs for students. From cricket to athletics, we foster a spirit of healthy competition and teamwork.',
    recruitmentActive: true,
    achievements: [
      { id: 'd1', title: 'RGPV Inter-College Cricket Champions', description: 'Won RGPV zonal cricket tournament 2024', date: '2024-02-15' },
      { id: 'd2', title: 'State Level Athletics – 3 Gold Medals', description: 'Students won gold in 100m, Long Jump and Shot Put', date: '2024-01-25' },
      { id: 'd3', title: 'Annual Sports Week', description: 'Successfully organized 7-day sports week with 800+ student participation', date: '2024-03-01' },
    ],
    customSections: [
      { id: 'sc1', title: 'Facilities', content: 'Cricket ground, Football field, Basketball court, Volleyball court, Indoor badminton, Table tennis, Gymnasium, and 400m athletics track.', iconName: 'Trophy' },
      { id: 'sc2', title: 'Upcoming Tournaments', content: 'Inter-branch Football League, Badminton Open, Table Tennis Championship, and Annual Marathon "Run for MITS".', iconName: 'Flag' },
    ],
    certificateConfig: {
      templateId: 'classic',
      showMITSLogo: true,
      showClubLogo: true,
      signatureTextFaculty: 'Prof. Rajesh Bharti - Faculty Coordinator',
      signatureTextPresident: 'Vikram Tiwari - Sports Secretary',
    },
  },
];

// ─── EVENTS ──────────────────────────────────────────────────────────────────
export const EVENTS: Event[] = [
  {
    id: 'evt-001',
    clubId: 'club-csit',
    title: 'HackMITS 2024',
    description: '36-hour hackathon open to all MITS students. Build innovative solutions to real-world problems. Prizes worth ₹50,000!',
    type: 'Free',
    status: 'Approved',
    date: '2024-04-20',
    bannerUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800',
  },
  {
    id: 'evt-002',
    clubId: 'club-csit',
    title: 'Web Dev Bootcamp',
    description: 'Intensive 2-day bootcamp on full-stack web development using React and Node.js. Includes hands-on projects and certification.',
    type: 'Paid',
    fee: 200,
    status: 'Approved',
    date: '2024-05-10',
    bannerUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
  },
  {
    id: 'evt-003',
    clubId: 'club-robo',
    title: 'RoboWars 2024',
    description: 'Battle of robots! Build your bot and compete against other teams in the arena. Teams of 2-4 allowed.',
    type: 'Free',
    status: 'Approved',
    date: '2024-03-25',
    bannerUrl: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=800',
  },
  {
    id: 'evt-004',
    clubId: 'club-cultural',
    title: 'Rangmanch – Annual Cultural Fest',
    description: 'The biggest cultural festival of MITS featuring dance, music, drama and literary competitions. 3 days of non-stop entertainment!',
    type: 'Free',
    status: 'Approved',
    date: '2024-04-05',
    bannerUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
  },
  {
    id: 'evt-005',
    clubId: 'club-sports',
    title: 'Inter-College Cricket Tournament',
    description: 'T20 cricket tournament between engineering colleges of Gwalior region. Winner takes the MITS Trophy!',
    type: 'Free',
    status: 'Approved',
    date: '2024-03-30',
    bannerUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
  },
  {
    id: 'evt-006',
    clubId: 'club-csit',
    title: 'AI/ML Workshop',
    description: 'Hands-on workshop on Machine Learning using Python, scikit-learn and TensorFlow. Build your first ML model!',
    type: 'Paid',
    fee: 150,
    status: 'Approved',
    date: '2024-06-01',
    bannerUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800',
  },
  {
    id: 'evt-007',
    clubId: 'club-csit',
    title: 'Cybersecurity Awareness Workshop',
    description: 'Learn about ethical hacking, penetration testing, and cybersecurity best practices. Includes CTF challenges!',
    type: 'Free',
    status: 'Approved',
    date: '2024-06-15',
    bannerUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
  },
  {
    id: 'evt-008',
    clubId: 'club-robo',
    title: 'IoT Bootcamp – Smart Campus',
    description: 'Learn to build IoT solutions using Arduino, ESP32 and Raspberry Pi. Build a smart campus prototype in 2 days.',
    type: 'Paid',
    fee: 300,
    status: 'Approved',
    date: '2024-07-05',
    bannerUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800',
  },
  {
    id: 'evt-009',
    clubId: 'club-cultural',
    title: 'Poetry Slam – Open Mic Night',
    description: 'Express yourself through poetry, spoken word, and storytelling. Open to all MITS students. Refreshments provided!',
    type: 'Free',
    status: 'Approved',
    date: '2024-05-20',
    bannerUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
  },
  {
    id: 'evt-010',
    clubId: 'club-sports',
    title: 'Yoga & Fitness Camp',
    description: 'Week-long morning yoga and fitness camp. Improve your health and well-being. Led by certified fitness trainers.',
    type: 'Free',
    status: 'Pending',
    date: '2024-06-10',
    bannerUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
  },
  {
    id: 'evt-011',
    clubId: 'club-csit',
    title: 'Open Source Contribution Day',
    description: 'Get started with open source! Learn Git, GitHub, and make your first PR to popular repos. Mentors available.',
    type: 'Free',
    status: 'Approved',
    date: '2024-05-25',
    bannerUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800',
  },
  {
    id: 'evt-012',
    clubId: 'club-cultural',
    title: 'Photography Walk – Heritage Gwalior',
    description: 'Capture the beauty of Gwalior Fort, Jai Vilas Palace and old city. Best photos exhibited in campus gallery.',
    type: 'Paid',
    fee: 100,
    status: 'Approved',
    date: '2024-06-20',
    bannerUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
  },
];


// ─── REGISTRATIONS ────────────────────────────────────────────────────────────
export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-001',
    eventId: 'evt-001',
    studentId: 'demo-student-001',
    studentName: 'Aryan Sharma',
    studentRoll: '0901CS211001',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT001-ARYAN',
    attendanceMarked: true,
  },
  {
    id: 'reg-002',
    eventId: 'evt-001',
    studentId: 'stu-002',
    studentName: 'Sneha Jain',
    studentRoll: '0901CS211002',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT001-SNEHA',
    attendanceMarked: false,
  },
  {
    id: 'reg-003',
    eventId: 'evt-002',
    studentId: 'demo-student-001',
    studentName: 'Aryan Sharma',
    studentRoll: '0901CS211001',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'UPI',
    ticketId: 'TKT-EVT002-ARYAN',
    attendanceMarked: false,
  },
  {
    id: 'reg-004',
    eventId: 'evt-003',
    studentId: 'stu-003',
    studentName: 'Rahul Mishra',
    studentRoll: '0901EC211003',
    studentBranch: 'Electronics & Communication',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT003-RAHUL',
    attendanceMarked: true,
  },
  {
    id: 'reg-005',
    eventId: 'evt-004',
    studentId: 'stu-004',
    studentName: 'Anjali Gupta',
    studentRoll: '0901CE211004',
    studentBranch: 'Civil Engineering',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT004-ANJALI',
    attendanceMarked: false,
  },
  {
    id: 'reg-006',
    eventId: 'evt-002',
    studentId: 'stu-006',
    studentName: 'Pooja Choudhary',
    studentRoll: '0901CS211006',
    studentBranch: 'Computer Science & IT',
    status: 'Pending',
    paymentType: 'UPI',
    attendanceMarked: false,
  },
  {
    id: 'reg-007',
    eventId: 'evt-005',
    studentId: 'stu-005',
    studentName: 'Vikram Tiwari',
    studentRoll: '0901ME211005',
    studentBranch: 'Mechanical Engineering',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT005-VIKRAM',
    attendanceMarked: true,
  },
  {
    id: 'reg-008',
    eventId: 'evt-007',
    studentId: 'stu-002',
    studentName: 'Sneha Jain',
    studentRoll: '0901CS211002',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT007-SNEHA',
    attendanceMarked: false,
  },
  {
    id: 'reg-009',
    eventId: 'evt-008',
    studentId: 'stu-007',
    studentName: 'Amit Dubey',
    studentRoll: '0901EE211007',
    studentBranch: 'Electrical Engineering',
    status: 'Approved',
    paymentType: 'UPI',
    ticketId: 'TKT-EVT008-AMIT',
    attendanceMarked: false,
  },
  {
    id: 'reg-010',
    eventId: 'evt-009',
    studentId: 'stu-008',
    studentName: 'Kavya Sharma',
    studentRoll: '0901CS221008',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT009-KAVYA',
    attendanceMarked: true,
  },
  {
    id: 'reg-011',
    eventId: 'evt-011',
    studentId: 'demo-student-001',
    studentName: 'Aryan Sharma',
    studentRoll: '0901CS211001',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT011-ARYAN',
    attendanceMarked: true,
  },
  {
    id: 'reg-012',
    eventId: 'evt-004',
    studentId: 'stu-008',
    studentName: 'Kavya Sharma',
    studentRoll: '0901CS221008',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'Free',
    ticketId: 'TKT-EVT004-KAVYA',
    attendanceMarked: true,
  },
  {
    id: 'reg-013',
    eventId: 'evt-012',
    studentId: 'stu-004',
    studentName: 'Anjali Gupta',
    studentRoll: '0901CE211004',
    studentBranch: 'Civil Engineering',
    status: 'Approved',
    paymentType: 'UPI',
    ticketId: 'TKT-EVT012-ANJALI',
    attendanceMarked: false,
  },
  {
    id: 'reg-014',
    eventId: 'evt-006',
    studentId: 'stu-006',
    studentName: 'Pooja Choudhary',
    studentRoll: '0901CS211006',
    studentBranch: 'Computer Science & IT',
    status: 'Approved',
    paymentType: 'UPI',
    ticketId: 'TKT-EVT006-POOJA',
    attendanceMarked: true,
  },
];

// ─── APPLICANTS ──────────────────────────────────────────────────────────────
export const INITIAL_APPLICANTS: Applicant[] = [
  {
    id: 'app-001',
    name: 'Rohit Saxena',
    rollNumber: '0901CE221009',
    branch: 'Civil Engineering',
    domain: 'Web Development',
    stage: 'Interview',
    whyJoin: 'I want to learn web development and contribute to CSIT Club projects.',
    recruitmentCycle: '2024-Spring',
  },
  {
    id: 'app-002',
    name: 'Priya Singh',
    rollNumber: '0901EC221010',
    branch: 'Electronics & Communication',
    domain: 'Embedded Systems',
    stage: 'Selected',
    whyJoin: 'Passionate about robotics and automation. Want to work on real-world IoT projects.',
    recruitmentCycle: '2024-Spring',
  },
  {
    id: 'app-003',
    name: 'Manish Yadav',
    rollNumber: '0901CS221011',
    branch: 'Computer Science & IT',
    domain: 'Machine Learning',
    stage: 'Screening',
    whyJoin: 'Interested in AI/ML and want to build projects with the club.',
    recruitmentCycle: '2024-Spring',
  },
  {
    id: 'app-004',
    name: 'Swati Pathak',
    rollNumber: '0901CE221012',
    branch: 'Civil Engineering',
    domain: 'Content & Media',
    stage: 'Applied',
    whyJoin: 'Love writing and want to handle the club blog and social media.',
    recruitmentCycle: '2024-Spring',
  },
  {
    id: 'app-005',
    name: 'Deepak Verma',
    rollNumber: '0901ME221013',
    branch: 'Mechanical Engineering',
    domain: 'Mechanical Design',
    stage: 'Offer',
    whyJoin: 'Want to combine mechanical and electronics skills in robotics projects.',
    recruitmentCycle: '2024-Spring',
  },
];

// ─── AUDIT LOGS ──────────────────────────────────────────────────────────────
export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2024-03-15 09:12:44',
    user: 'Admin (Demo)',
    action: 'System initialized. CCMS demo mode activated.',
  },
  {
    id: 'log-002',
    timestamp: '2024-03-15 09:14:02',
    user: 'Admin (Demo)',
    action: 'Club "CSIT Club" created and configured.',
    clubId: 'club-csit',
  },
  {
    id: 'log-003',
    timestamp: '2024-03-15 09:15:30',
    user: 'Admin (Demo)',
    action: 'Club "Robotics Club" created and configured.',
    clubId: 'club-robo',
  },
  {
    id: 'log-004',
    timestamp: '2024-03-15 09:16:10',
    user: 'Admin (Demo)',
    action: 'Aryan Sharma appointed as President of CSIT Club.',
    clubId: 'club-csit',
  },
  {
    id: 'log-005',
    timestamp: '2024-03-16 10:00:00',
    user: 'Aryan Sharma',
    action: 'Registered for HackMITS 2024 — Ticket Issued.',
    clubId: 'club-csit',
  },
  {
    id: 'log-006',
    timestamp: '2024-03-16 10:05:11',
    user: 'Aryan Sharma',
    action: 'Registered for Web Dev Bootcamp — Pending Payment.',
    clubId: 'club-csit',
  },
  {
    id: 'log-007',
    timestamp: '2024-03-16 11:20:05',
    user: 'Dr. Priya Verma',
    action: 'Event "Rangmanch – Annual Cultural Fest" approved.',
    clubId: 'club-cultural',
  },
  {
    id: 'log-008',
    timestamp: '2024-03-16 12:00:00',
    user: 'Admin (Demo)',
    action: '14 institutional identities seeded into the ledger.',
  },
];
